### ISSUE TITLE
Make the KnotBuilder (or DSL) more extensible

### ISSUE THREAD

**Issue by StefMa** [beworker/knot#41]
We want to log each `state`, `change` and `action` changes.
In the past we simply used something like this to print it to logcat:
```kotlin
        knot<A,B,C> {
            state {
                watchAll { TAG.logDebug { "|  state: $it" } }
                initial = ...
            }
            changes {
                watchAll {
                    TAG.logDebug { "+----------------" }
                    TAG.logDebug { "| change: $it" }
                }
                reduce { ... }
            }
            actions {
                watchAll { TAG.logDebug { "| action: $it" } }
                perform<...> { ... }
            }
        }
```
But we don't want to repeat these log statements in every class were we use knot.
So we thought about another implementation like a `fun <A,B,C> loggableKnot<A,B,C>(block: ...): KnotBuilder<A,B,C>` But this is not going to work because each time we call the `state`, `change` or `action` lambda a **new** instance of the `StateBuilder` resp. `ChangeBuilder` and `ActionBuilder` will be created.

That means it is currently *not* possible to override (or better **add**) "something" to these builders "behind the scene".

The only solution we found was to have a extension function for each `Builder` (`State`, `Change`, `Action`):
Example:
```kotlin
fun <State : Any> StateBuilder<State>.logState(tag: String) {
    watchAll { tag.logInfo { "|  state: $it" } }
}
```
But this looks of course not so nice in the knot DSL:
```kotlin
        knot<A,B,C> {
            state {
                logState(TAG)
                initial = ...
            }
            changes {
                logChanges(TAG)
                reduce { ... }
            }
            actions {
                logActions(TAG)
                perform<...> { ... }
            }
        }
```

So what I want to have is something like this:
```kotlin
fun <State : Any, Change : Any, Action : Any> KnotBuilder<State, Change, Action>.logEverything(tag: String) {
    state {
        watchAll { tag.logInfo { "|  state: $it" } }
    }
    changes {
        watchAll {
            tag.logInfo { "+----------------" }
            tag.logInfo { "| change: $it" }
        }
    }
    actions {
        watchAll { tag.logDebug { "| action: $it" } }
    }
}
```
But again, these will override each `StateBuilder`, `ChangesBuilder` and `ActionsBuilder`.. But instead of overriding I want to "add" these things..

Or is there a another/better solution for something like this?

**Comment by beworker** [comment]
You could create a custom builder function like the one below, which adds logger logic before the execution of the actual knot builder block.

```kotlin
fun <State : Any, Change : Any, Action : Any> knotWithLogger(
    block: KnotBuilder<State, Change, Action>.() -> Unit
): Knot<State, Change> =
    KnotBuilder<State, Change, Action>()
        .apply {
            state {
                watchAll { tag.logInfo { "|  state: $it" } }
            }
            changes {
                watchAll {
                    tag.logInfo { "+----------------" }
                    tag.logInfo { "| change: $it" }
                }
            }
            actions {
                watchAll { tag.logDebug { "| action: $it" } }
            }
        }
        .also(block)
        .build()
```

Then you can use this function instead of the default `knot<State, Change, Action>` one like this.

```knot
val knotWithLogger =
    knotWithLogger<State, Change, Action> {
        state { ... }
        changes { ... }
        actions { ... }
    }
```

Would it work for you?

**Comment by beworker** [comment]
I haven't realized right away, that the KnotBuilder's constructor is internal and cannot be called in the app. That's why we should stick to the `knot<State, Change, Action> {}` builder function. The updated version of the `knotWithLogger` function below is not much different from the original one.

```kotlin
fun <State : Any, Change: Any, Action: Any> knotWithLogger(
    block: KnotBuilder<State, Change, Action>.() -> Unit
): Knot<State, Change> =
    knot<State, Change, Action> {
        state {
            watchAll { logInfo { "|  state: $it" } }
        }
        changes {
            watchAll {
                logInfo { "+----------------" }
                logInfo { "| change: $it" }
            }
        }
        actions {
            watchAll { logDebug { "| action: $it" } }
        }
        block()
    }
```

Hope it helps.

**Comment by StefMa** [comment]
Oh nice.
Thank you for the quit answer.
I was confused because I thought calling calling the `state(block: ..)` function the second time it would *override* the first one. But it doesn't. The `StateBuilder` will be created again, but the `list` with the `stateInterceptors` are the same.
So it will work like you suggested [here](https://github.com/beworker/knot/issues/41#issuecomment-666348277).

Thank you and have nice day 👍 🙂
